name: Android CI
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Install NDK
        run: echo "y" | sudo /usr/local/lib/android/sdk/tools/bin/sdkmanager --install "ndk;20.0.5594570" --sdk_root=${ANDROID_SDK_ROOT}

      - name: Build with Gradle
        run: ./gradlew build

      - name: build release
        run: ./gradlew assembleRelease
      - name: list files
        run: ls -lrt app/build/outputs/apk/release

      - name: upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.2.1
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          token: ${{secrets.FIREBASE_TOKEN}}
          groups: testers
          file: app/build/outputs/apk/release/app-release.apk








#on:
#  pull_request:
#    branches:
#      - main
#      - master
#  push:
#    branches:
#      - main
#      - master
#      - develop
#name: "Build & Release"
#jobs:
#  build:
#    name: Build & Release
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v1
#      - uses: actions/setup-java@v1
#        with:
#          java-version: '12.x'
#      - uses: subosito/flutter-action@v1
#        with:
#          flutter-version: '3.10.5'
#      - run: flutter pub get
#      #      - run: flutter test
#      - run: flutter build apk --release
##      - run: |
##          flutter build ios --no-codesign
##          cd build/ios/iphoneos
##          mkdir Payload
##          cd Payload
##          ln -s ../Runner.app
##          cd ..
##          zip -r app.ipa Payload
#      - name: Push to Releases
#        uses: ncipollo/release-action@v1
#        with:
#          artifacts: "build/app/outputs/apk/release/*"
#          tag: v1.0.${{ github.run_number }}
#          token: ${{ secrets.TOKEN }}
#
#
#      # Uploads the app to Firebase App Distribution
#      - name: Upload to Firebase App Distribution
#        uses: wzieba/Firebase-Distribution-Github-Action@v1
#        with:
#          appId: ${{secrets.FIREBASE_APP_ID}}
#          token: ${{secrets.FIREoBASE_TOKEN}}
#      # You can create groups on Firebase console to share the apk
#          groups: testers
#          file: build/app/outputs/flutter-apk/app-release.apk
#
#
#
##          artifacts: "build/app/outputs/apk/debug/*,build/ios/iphoneos/app.ipa"
#
