on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master
      - develop
name: "Build & Release"
jobs:
  build:
    name: Build & Release
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.10.5'
      - run: flutter pub get
      #      - run: flutter test
      - run: flutter build apk --release
      #      - run: |
      #          flutter build ios --no-codesign
      #          cd build/ios/iphoneos
      #          mkdir Payload
      #          cd Payload
      #          ln -s ../Runner.app
      #          cd ..
      #          zip -r app.ipa Payload
      - name: Upload to code coverage
        uses: codecov/codecov-action@v1.2.2
        with:
          token: ${{secrets.TOKEN}}
          file: coverage/lcov.info

      - name: Push to Releases
        uses: actions/upload-artifact@v3
        with:
          name: release-apk
          path: build/app/outputs/apk/release/app-release.apk

#        uses: ncipollo/release-action@v1
#        with:
#          artifacts: "build/app/outputs/apk/debug/*"
#          tag: v1.0.${{ github.run_number }}
#          token: ${{ secrets.TOKEN }}
#

#          artifacts: "build/app/outputs/apk/debug/*,build/ios/iphoneos/app.ipa"



# push to master, main, develop
# pull request on main master