on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master
      - develop
name: "Build & Release"
jobs:
  build:
    name: Build & Release
    runs-on: macos-latest
    steps:
#      - name: Download APK from build
#        uses: actions/download-artifact@v1
#        with:
#          name: apk
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
#        env:
#          token: ${{ secrets.TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          token: ${{ secrets.TOKEN }}
      - name: Upload Release APK
        id: upload_release_asset
        uses: actions/upload-release-asset@v1.0.1
#        env:
#          token: ${{ secrets.TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: apk/app-debug.apk
          asset_name: MensaApp.apk
          asset_content_type: application/zip
          token: ${{ secrets.TOKEN }}

#        uses: ncipollo/release-action@v1
#        with:
#          artifacts: "build/app/outputs/apk/debug/*"
#          tag: v1.0.${{ github.run_number }}
#          token: ${{ secrets.TOKEN }}
#

#          artifacts: "build/app/outputs/apk/debug/*,build/ios/iphoneos/app.ipa"



# push to master, main, develop
# pull request on main master